# This is a stub configuration file for the CxOneFlow Resolver Agent.
# Please provide your required configuration options.

# The resolver agent starts via systemd.  The systemd service will
# not start until this file contains an actionable configuration.

# Some configuration options allow the name of a secret rather than
# an explicit value.  This is the path where a file with the secret
# name should be located.

# The resolver agent runs as user "resolver" that is in group
# "resolver".  The secret directory should have permissions
# set as 500 owned by "resolver:resolver".  The contents inside the
# secret directory should be owned by "resolver:resolver" 
# with permissions 400.
secret-root-path: /var/secrets

# The 'resolver-work-path' option should be set to a directory
# owned by 'root:resolver' with permissions 770.

# This is the element where this agents serviced tags are
# configured. Please consult the CxOneFlow documentation
# for details:
#
# https://github.com/checkmarx-ts/cxone-flow
serviced-tags:
