#!/bin/sh

case $1 in
  "remove")
    systemctl is-enabled --quiet cxoneflow-scan-agent
    [ $? -eq 0 ] && systemctl disable cxoneflow-scan-agent || :
    ;;

  "purge")
    getent passwd cx-scan-agent-rt > /dev/null
    if [ $? -eq 0 ];
    then
      echo Removing 'cx-scan-agent-rt' user
      userdel cx-scan-agent-rt
    fi

    getent passwd cx-scan-agent > /dev/null
    if [ $? -eq 0 ];
    then
      echo Removing 'cx-scan-agent' user/group
      userdel cx-scan-agent
    fi
    ;;

  *)
    ;;

esac
