#!/bin/sh


systemctl is-active --quiet cxoneflow-resolver-agent
if [ $? -eq 0 ];
then
  echo "#############################################################################################"
  echo Please purge the previous install of cxoneflow-resolver-agent before installing this package.
  echo "#############################################################################################"
  exit 1
fi
